### ISSUE TITLE
Use of node-red-node- package name

### ISSUE THREAD

**Issue by knolleary** [zetxx/node-red-node-file-upload#3]
Hi,

our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging.html) suggest that 3rd parties avoid using the `node-red-node` prefix and consider using the `node-red-contrib` prefix to their npm name to avoid confusion with ones maintained by the project itself.

Just wanted to flag this up and ask if you'd consider republishing your package to npm under the alternative name.

Thanks,
Nick

**Comment by zetxx** [comment]
done, thanks

**Comment by knolleary** [comment]
Thank you!
